const show=(tl,incoming,at)=>tl.set(incoming,{opacity:1},at);
const swap=(tl,outgoing,incoming,at)=>{tl.set(incoming,{opacity:1},at);tl.set(outgoing,{opacity:0},at);return tl};
export const signalDeskTransitions={
  ribbonHandoff(tl,{outgoing,incoming,ribbon},at,d=.72){show(tl,incoming,at);tl.fromTo(ribbon,{xPercent:-105,skewX:-8},{xPercent:105,skewX:0,duration:d,ease:"expo.inOut"},at);tl.to(outgoing,{x:-120,opacity:.28,duration:d,ease:"power3.inOut"},at);tl.fromTo(incoming,{x:210,clipPath:"inset(0 0 0 22%)"},{x:0,clipPath:"inset(0 0 0 0%)",duration:d*.66,ease:"power4.out"},at+d*.34);return tl},
  headlinePush(tl,{outgoing,incoming,headline},at,d=.68){show(tl,incoming,at);tl.fromTo(headline,{xPercent:100,scaleX:1.35},{xPercent:-100,scaleX:1,duration:d,ease:"expo.inOut"},at);tl.to(outgoing,{y:-100,clipPath:"inset(0 0 48% 0)",duration:d*.55,ease:"power3.in"},at);tl.fromTo(incoming,{y:130,clipPath:"inset(50% 0 0 0)"},{y:0,clipPath:"inset(0 0 0 0)",duration:d*.55,ease:"power4.out"},at+d*.35);return tl},
  deskCross(tl,{outgoing,incoming,rails},at,d=.74){show(tl,incoming,at);tl.fromTo(rails,{scaleX:0},{scaleX:1,duration:d*.44,stagger:.045,ease:"expo.in",transformOrigin:"left center"},at);tl.to(outgoing,{scale:.965,opacity:.18,duration:d*.54,ease:"power2.in"},at);tl.fromTo(incoming,{scale:1.04,opacity:0},{scale:1,opacity:1,duration:d*.5,ease:"power3.out"},at+d*.42);tl.to(rails,{scaleX:0,duration:d*.34,stagger:.035,ease:"expo.out",transformOrigin:"right center"},at+d*.58);return tl},
  feedRise(tl,{outgoing,incoming,rows},at,d=.7){show(tl,incoming,at);tl.fromTo(rows,{y:240,opacity:1},{y:-240,duration:d,stagger:.04,ease:"power3.inOut"},at);tl.to(outgoing,{y:-86,opacity:.18,duration:d*.56,ease:"power2.in"},at);tl.fromTo(incoming,{y:110,opacity:0},{y:0,opacity:1,duration:d*.5,ease:"power4.out"},at+d*.42);return tl},
  timecodeJump(tl,{outgoing,incoming,timecode},at,d=.76){show(tl,incoming,at);tl.fromTo(timecode,{scale:1,x:0},{scale:5.8,x:-460,duration:d*.47,ease:"power4.in"},at);swap(tl,outgoing,incoming,at+d*.47);tl.fromTo(incoming,{clipPath:"inset(45% 0 45% 0)"},{clipPath:"inset(0 0 0 0)",duration:d*.53,ease:"expo.out"},at+d*.47);tl.to(timecode,{scale:1,x:0,opacity:0,duration:d*.38,ease:"power3.out"},at+d*.48);return tl},
  bulletinShutter(tl,{outgoing,incoming,slats},at,d=.78){show(tl,incoming,at);tl.fromTo(slats,{scaleY:0},{scaleY:1,duration:d*.42,stagger:.035,ease:"power4.in",transformOrigin:"top"},at);swap(tl,outgoing,incoming,at+d*.46);tl.set(slats,{transformOrigin:"bottom"},at+d*.46);tl.to(slats,{scaleY:0,duration:d*.45,stagger:{each:.03,from:"end"},ease:"power4.out"},at+d*.46);return tl},
  sourceStack(tl,{outgoing,incoming,cards},at,d=.8){show(tl,incoming,at);tl.fromTo(cards,{x:1920,rotationZ:2},{x:-1920,rotationZ:-1,duration:d,stagger:.055,ease:"expo.inOut"},at);tl.to(outgoing,{x:-130,scale:.97,opacity:.2,duration:d*.6,ease:"power3.in"},at);tl.fromTo(incoming,{x:130,scale:1.02,opacity:0},{x:0,scale:1,opacity:1,duration:d*.48,ease:"power4.out"},at+d*.45);return tl},
  signalCut(tl,{outgoing,incoming,signal,rings},at,d=.68){show(tl,incoming,at);tl.fromTo(signal,{scale:.1,opacity:0},{scale:1,opacity:1,duration:d*.38,ease:"back.out(1.6)"},at);tl.fromTo(rings,{scale:.2,opacity:.9},{scale:7,opacity:0,duration:d*.64,stagger:.05,ease:"power3.out"},at+.08);tl.to(outgoing,{clipPath:"circle(0% at 78% 22%)",duration:d*.52,ease:"power4.in"},at+.08);tl.fromTo(incoming,{clipPath:"circle(0% at 78% 22%)"},{clipPath:"circle(145% at 78% 22%)",duration:d*.48,ease:"power4.out"},at+d*.34);tl.to(signal,{scale:.7,opacity:0,duration:d*.2,ease:"power2.out"},at+d*.62);return tl},
  breakingFlash(tl,{outgoing,incoming,flash,banner},at,d=.58){show(tl,incoming,at);tl.fromTo(flash,{opacity:0,scaleY:.04},{opacity:1,scaleY:1,duration:d*.32,ease:"expo.in",transformOrigin:"center"},at);swap(tl,outgoing,incoming,at+d*.34);tl.fromTo(banner,{xPercent:-110,skewX:-12},{xPercent:110,skewX:0,duration:d*.7,ease:"expo.inOut"},at+.04);tl.to(flash,{opacity:0,scaleY:.04,duration:d*.3,ease:"expo.out"},at+d*.36);return tl},
  headlineCrush(tl,{outgoing,incoming,words},at,d=.72){show(tl,incoming,at);tl.to(outgoing,{scaleX:.12,filter:"blur(10px)",opacity:.2,duration:d*.46,ease:"power4.in",transformOrigin:"left center"},at);tl.fromTo(words,{scaleX:3.2,x:420,opacity:0},{scaleX:1,x:0,opacity:1,duration:d*.55,stagger:.045,ease:"expo.out",transformOrigin:"left center"},at+d*.31);tl.fromTo(incoming,{clipPath:"inset(0 0 0 92%)"},{clipPath:"inset(0 0 0 0%)",duration:d*.5,ease:"power4.out"},at+d*.34);tl.to(words,{x:-70,scaleX:.9,opacity:0,duration:d*.16,stagger:.025,ease:"power2.out"},at+d*.82);return tl},
  mapAperture(tl,{outgoing,incoming,aperture,markers},at,d=.82){show(tl,incoming,at);tl.fromTo(aperture,{clipPath:"polygon(50% 50%,50% 50%,50% 50%,50% 50%)",rotation:8},{clipPath:"polygon(0 8%,92% 0,100% 92%,8% 100%)",rotation:0,duration:d*.62,ease:"expo.inOut"},at);tl.to(outgoing,{scale:1.13,filter:"blur(8px)",opacity:.15,duration:d*.62,ease:"power3.in"},at);tl.fromTo(markers,{scale:0,opacity:0},{scale:1,opacity:1,duration:d*.32,stagger:.06,ease:"back.out(1.7)"},at+d*.5);tl.fromTo(incoming,{scale:.93,opacity:0},{scale:1,opacity:1,duration:d*.42,ease:"power3.out"},at+d*.4);tl.to(aperture,{opacity:0,duration:d*.22,ease:"power2.out"},at+d*.62);tl.to(markers,{scale:.7,opacity:0,duration:d*.18,stagger:.025,ease:"power2.out"},at+d*.78);return tl},
  dataCollapse(tl,{outgoing,incoming,bars,datum},at,d=.78){show(tl,incoming,at);tl.fromTo(bars,{scaleY:1,opacity:1},{scaleY:.04,opacity:0,duration:d*.3,stagger:{each:.025,from:"edges"},ease:"power4.in",transformOrigin:"bottom"},at);tl.to(outgoing,{clipPath:"inset(46% 0 46% 0)",opacity:.3,duration:d*.42,ease:"expo.in"},at+.08);tl.fromTo(datum,{scale:6,opacity:0,filter:"blur(12px)"},{scale:1,opacity:1,filter:"blur(0px)",duration:d*.46,ease:"expo.out"},at+d*.31);tl.fromTo(incoming,{clipPath:"inset(48% 0 48% 0)"},{clipPath:"inset(0 0 0 0)",duration:d*.5,ease:"power4.out"},at+d*.28);tl.to(datum,{scale:.9,opacity:0,duration:d*.14,ease:"power2.out"},at+d*.78);return tl}
};
export const signalDeskTransitionMeta={primary:["ribbon-handoff","headline-push","desk-cross","feed-rise"],section:["timecode-jump","bulletin-shutter","source-stack","signal-cut"],accent:["breaking-flash","headline-crush","map-aperture","data-collapse"]};
