const reveal=(tl,incoming,at)=>tl.set(incoming,{opacity:1},at);
const swap=(tl,outgoing,incoming,at)=>{tl.set(incoming,{opacity:1},at);tl.set(outgoing,{opacity:0},at)};
export const voxelHarnessTransitions={
  chunkPush(tl,{outgoing,incoming},at,duration=.56){reveal(tl,incoming,at);tl.fromTo(incoming,{x:1920},{x:0,duration,ease:"steps(8)"},at);tl.to(outgoing,{x:-1920,duration,ease:"steps(8)"},at);return tl},
  blockRise(tl,{outgoing,incoming},at,duration=.6){reveal(tl,incoming,at);tl.fromTo(incoming,{y:1080},{y:0,duration,ease:"steps(7)"},at);tl.to(outgoing,{y:-1080,duration,ease:"steps(7)"},at);return tl},
  portalCross(tl,{outgoing,incoming},at,duration=.78){tl.fromTo(incoming,{clipPath:"circle(0% at 50% 50%)",scale:.86,filter:"blur(8px)",opacity:1},{clipPath:"circle(145% at 50% 50%)",scale:1,filter:"blur(0px)",duration,ease:"power3.inOut"},at);tl.to(outgoing,{scale:1.12,filter:"blur(9px)",duration,ease:"power2.inOut"},at);return tl},
  cameraStep(tl,{outgoing,incoming},at,duration=.64){tl.fromTo(incoming,{scale:.72,x:190,opacity:0},{scale:1,x:0,opacity:1,duration,ease:"steps(8)"},at+duration*.14);tl.to(outgoing,{scale:1.34,x:-230,opacity:0,duration:duration*.72,ease:"power4.in"},at);return tl},
  craftGrid(tl,{outgoing,incoming,tiles},at,duration=.72){tl.fromTo(tiles,{scale:0,opacity:1},{scale:1,duration:duration*.46,stagger:.018,ease:"steps(3)"},at);swap(tl,outgoing,incoming,at+duration*.5);tl.to(tiles,{scale:0,duration:duration*.5,stagger:.014,ease:"steps(3)"},at+duration*.5);return tl},
  inventorySwap(tl,{outgoing,incoming,slots},at,duration=.68){tl.fromTo(slots,{y:160,opacity:0},{y:0,opacity:1,duration:duration*.5,stagger:.035,ease:"back.out(1.5)"},at);swap(tl,outgoing,incoming,at+duration*.5);tl.to(slots,{y:-160,opacity:0,duration:duration*.5,stagger:.035,ease:"power3.in"},at+duration*.5);return tl},
  terrainWipe(tl,{outgoing,incoming,columns},at,duration=.72){reveal(tl,incoming,at);tl.fromTo(columns,{scaleY:0,opacity:1},{scaleY:1,duration,stagger:.035,ease:"steps(6)",transformOrigin:"center bottom"},at);tl.to(outgoing,{opacity:0,duration:.08},at+duration*.56);return tl},
  commandCut(tl,{outgoing,incoming,overlay},at,duration=.58){tl.set(overlay,{opacity:1,backgroundColor:"#7bd14b",transformOrigin:"left center"},at);tl.fromTo(overlay,{scaleX:0},{scaleX:1,duration:duration*.48,ease:"steps(8)"},at);swap(tl,outgoing,incoming,at+duration*.48);tl.set(overlay,{transformOrigin:"right center"},at+duration*.5);tl.to(overlay,{scaleX:0,duration:duration*.5,ease:"steps(8)"},at+duration*.5);return tl},
  enderIris(tl,{outgoing,incoming},at,duration=.76){reveal(tl,incoming,at);tl.fromTo(incoming,{clipPath:"polygon(50% 50%,50% 50%,50% 50%,50% 50%)",rotation:.6},{clipPath:"polygon(-15% -15%,115% -15%,115% 115%,-15% 115%)",rotation:0,duration,ease:"power3.inOut"},at);tl.to(outgoing,{scale:1.08,rotation:-.4,filter:"blur(5px)",duration,ease:"power2.inOut"},at);return tl},
  blockShatter(tl,{outgoing,incoming,tiles},at,duration=.7){reveal(tl,incoming,at);tl.fromTo(tiles,{x:0,y:0,rotation:0,scale:1,opacity:1},{x:(i)=>((i%6)-2.5)*150,y:(i)=>(Math.floor(i/6)-1.5)*120,rotation:(i)=>(i%2?18:-18),scale:.45,opacity:0,duration,stagger:.012,ease:"power4.in"},at);tl.to(outgoing,{opacity:0,duration:.08},at+duration*.5);return tl},
  redstonePulse(tl,{outgoing,incoming,overlay},at,duration=.64){tl.set(overlay,{opacity:0,backgroundColor:"#e46f3a"},at);tl.to(overlay,{opacity:1,duration:duration*.38,ease:"steps(4)"},at);swap(tl,outgoing,incoming,at+duration*.42);tl.to(overlay,{opacity:0,duration:duration*.58,ease:"power3.out"},at+duration*.42);return tl},
  voxelFold(tl,{outgoing,incoming},at,duration=.72){reveal(tl,incoming,at);tl.fromTo(outgoing,{rotationY:0,x:0,opacity:1},{rotationY:-90,x:-220,opacity:0,duration,ease:"steps(8)",transformOrigin:"left center",transformPerspective:1200},at);tl.fromTo(incoming,{rotationY:90,x:220,opacity:1},{rotationY:0,x:0,duration:easeDuration(duration),ease:"steps(8)",transformOrigin:"right center",transformPerspective:1200},at);return tl}
};
const easeDuration=value=>value;
export const voxelHarnessTransitionMeta={primary:["chunk-push","block-rise","portal-cross","camera-step"],section:["craft-grid","inventory-swap","terrain-wipe","command-cut"],accent:["ender-iris","block-shatter","redstone-pulse","voxel-fold"]};

